<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage/Master.Master" AutoEventWireup="true" CodeBehind="ChatRoom.aspx.cs" Inherits="ZDSoft.CR.ChatRoom" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <%--<meta http-equiv="refresh" content="5"/> --%>
    <link href="Style/cssReset.css" rel="stylesheet" />
    <link href="Style/chatRoom.css" rel="stylesheet" />
    <style>
        #talkcount {
            height: 400px;
            border: solid black 1px;
            opacity: 0.7;
            overflow: auto;
        }

        #d {
            width: 100%;
            background-image: url(Images/chat1.jpg);
        }

        #d1 {
            width: 400px;
            margin: auto;
        }

        #d2 {
            width: 400px;
        }

        #talkmanager {
            width: 399px;
            height: 60px;
            border: solid black 1px;
        }

        .hidden {
            display: none;
        }
         .container {
            background-color: #99CCFF;
            border: thick solid #808080;
            padding: 20px;
            margin: 20px;
        }
    </style>   

</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
     <asp:Label ID="lb_roomId" runat="server" Text="Label"></asp:Label>
     <asp:Label ID="lb_UserId" runat="server" Text="Label"></asp:Label>
     <div>
        <asp:Button ID="btn_leaveRoom" runat="server" Text="离开房间" OnClick="btn_leaveRoom_Click" />
        管理员：
        <asp:Label ID="lbNickName" runat="server" Text="Label"></asp:Label>
        <asp:Button ID="btn_ChangeInformation" runat="server" Text="修改信息" OnClick="btn_ChangeInformation_Click" />
    </div>
    <%--<asp:ScriptManager ID="ScriptManager1" runat="server"></asp:ScriptManager>
    <div id="d">
        <div id="d1">
           
            <asp:UpdatePanel ID="UpdatePanel1" runat="server">
                <ContentTemplate>
                    <div id="d2">
                        <div id="talkcount">      
                            <div class="container">
                            <input type="text" id="message" />
                            <input type="hidden" id="displayname" />
                            <asp:TextBox ID="tb_roomId" runat="server"></asp:TextBox>
                            <ul id="discussion">
                            </ul>
                           </div>
                        </div>
                        <div style="width: 395px; opacity: 0.6;">
                            <div style="width: 399px; margin-left: 359px;">
                                <input type="button" id="sendmessage" value="发送" />                             
                            </div>
                        </div>
                    </div>
                </ContentTemplate>
            </asp:UpdatePanel>
            <div style="width: 395px; opacity: 0.6; position: relative; top: -60px;">
                <asp:TextBox ID="tbxMsgContent" runat="server" TextMode="MultiLine" Width="100%"></asp:TextBox>
            </div>
        </div>
    </div>--%>
    <!--Script references. -->
    <!--Reference the jQuery library. -->
    <script src="Scripts/jquery-1.6.4.min.js" ></script>
    <!--Reference the SignalR library. -->
    <script src="Scripts/jquery.signalR-2.2.0.min.js"></script>
    <!--Reference the autogenerated SignalR hub script. -->
    <script src="signalr/hubs"></script>
    <!--Add script to update the page and send messages.--> 
    <script type="text/javascript">
        var clients = [];
        var chat;
        var roomId = $("#ContentPlaceHolder1_lb_roomId").html();
        $(function () {
            chat = $.connection.ChatHub;
            console.info(chat);
            //显示提示方法  
            chat.client.showMessage = function (message) {
                alert(message);
            }
            //注册显示信息的方法  
            chat.client.addMessage = function (message, connectionId) {
                //debugger
                if ($.inArray(connectionId, clients) == -1) {
                    showWin(connectionId);
                }
                $("#" + connectionId).find("ul").each(function () {
                    $(this).append('<li>' + message + '</li>');
                })
            }
            //注册显示所有用户的方法  
            chat.client.getUsers = function (data) {
                if (data) {
                    var json = $.parseJSON(data);
                    console.info(json);
                    $("#users").html("");
                    for (var i = 0; i < json.length; i++) {
                        var html = "";
                        if (json[i].RommId == roomId) {
                            html += '<div class="friends">';
                            html += '<img class="portrait" src=' + json[i].HeadUrl + ' alt="头像" />';
                            html += ' <p class="nc">' + json[i].NickName + '</p>';
                            html += ' <p class="statu">[在线]</p>';
                            html += '</div>';
                        }
                        //var html = '<li>用户名:' + json[i].UserName + '<input type="button" connectionId="' + json[i].ConnectionID +   '"value="聊天" onclick="userChat(this)"/>';
                        $("#users").append(html);
                    }
                }
            }
            //注册显示推出聊天提示的方法  
            chat.client.exitUser = function (data) {
                alert(data);
            }

            //注册显示个人信息的方法  
            chat.client.showId = function (data) {
                $("#conId").html(data);
                clients.push(data);
            }

            //获取用户名称  
            //$('#userName').html(prompt('请输入您的名称', ''));
            //连接成功后获取自己的信息  
            $.connection.hub.start().done(function () {
                var userId = $("#ContentPlaceHolder1_lb_UserId").html();
                chat.server.getName(userId, roomId);
            });
        });  
        //开始聊天  
        function userChat(obj) {
            var connectionId = $(obj).attr('connectionId');
            showWin(connectionId);
        }
        function showWin(connectionId) {
            //var connectionId = $(obj).attr('connectionId');  
            clients.push(connectionId);
            var html = '<div style="float:left;margin-left:30px;border:double" id="' + connectionId + '" connectionId="' + connectionId + '">' + connectionId + '"的房间聊天记录如下:<input type="button" onclick="exitChat(this)" value="退出"/><ul></ul><input type="text" /> <input type="button" value="发送" onclick="sendMessage(this)" /></div>';
            $("#userBox").append(html);
        }
        function exitChat(btnObj) {
            //debugger
            //  var connectionId = $(btnObj).parent().attr("connectionId");  
            $(btnObj).parent().remove();
            //chat.server.exitChat(connectionId);  
        }
        //发送消息  
        function sendMessage(data) {
            var message = $(data).prev().val();
            var userObj = $(data).parent();
            var username = $("#userName").html();
            message = username + ":" + message;
            console.info($(userObj).attr("connectionId"));
            var targetConnectionId = $(userObj).attr("connectionId");
            chat.server.sendMessage(targetConnectionId, message);
            $(data).prev().val("");
        }  
    </script>  
    <div class="header">
		<div class="header_portrait">
			<img class="portrait" src="Images/head_portrait.png" alt="头像" />
			<!-- 昵称 -->
			<p class="nc">夏天</p>
			<!-- 个性签名 -->
			<p class="gq" style="margin-top: 10px;">欲穷千里目</p>
		</div>
	</div>

	<div class="content">
		<!-- 列表 -->
		<div class="list">
			<div class="head">
				<h1>联系人</h1>
				<span class="search"></span>
			</div>
			<div id="users" style="overflow-y: scroll; height: 495px;">
				<%--<div class="friends">
			    <img src="Images/quannengqiang.png" alt="全能墙" class="portrait" />
			        <p class="nc">全能墙</p>
			        <p class="statu">[在线]</p>
				</div>	--%>	
			</div>
		</div>

		<!-- 窗口 -->
		<div class="chatWindow">
			<div class="head">
				<h1>全能墙</h1>
				<span class="close"></span>
			</div>
			<div class="chatcontent">
				<footer class="inputtool">
					
				</footer>
			</div>
		</div>

	</div>



    <div>  
        <div>名称：<p id="userName"></p></div>  
        <div>ConnectionID:<p id="conId"></p></div>  
      
        <div style="width:25%;border:1px solid #ff0000">  
            <div>在线用户列表</div>  
            <%--<ul id="users"></ul>--%>
        </div>  
        <div id="userBox">

        </div>  
    </div>  
</asp:Content>
